# Generated by Django 2.2.17 on 2021-11-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('github', models.CharField(blank=True, default=None, max_length=256, null=True, unique=True, verbose_name='Сылка на Гитхаб')),
                ('vk', models.CharField(blank=True, default=None, max_length=256, null=True, unique=True, verbose_name='Сылка на vk')),
                ('facebook', models.CharField(blank=True, default=None, max_length=256, null=True, unique=True, verbose_name='Сылка на facebook')),
                ('instagram', models.CharField(blank=True, default=None, max_length=256, null=True, unique=True, verbose_name='Сылка на instagram')),
                ('telegram_username', models.CharField(blank=True, default=None, max_length=256, null=True, unique=True, verbose_name='имя пользователя для Телеграм')),
                ('whatsapp', models.CharField(blank=True, default=None, max_length=256, null=True, unique=True, verbose_name='Телефон для whatsapp')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('title', models.CharField(default='Default Title', max_length=120, verbose_name='Заголовок')),
                ('home', models.TextField(blank=True, verbose_name='Home')),
                ('image', models.ImageField(blank=True, upload_to='MainPhoto', verbose_name='фото/картинка')),
                ('show_image', models.BooleanField(default=True)),
                ('about', models.TextField(blank=True, verbose_name='about')),
            ],
            options={
                'verbose_name': 'контент на страницу главная',
                'verbose_name_plural': 'Главная (контент страницы)',
                'ordering': ('-created_at',),
            },
        ),
    ]
