# Generated by Django 2.2.17 on 2021-11-03 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainpage', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_settings', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('dark', models.BooleanField(default=False, verbose_name='Ночной режим')),
                ('background', models.CharField(blank=True, max_length=128, verbose_name='Background')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата Обновления')),
                ('addition_code', models.TextField(blank=True, verbose_name='Доп. код')),
                ('insert_addition_code', models.BooleanField(default=False, verbose_name='добавить код')),
            ],
            options={
                'verbose_name': 'Настройки страницы',
                'verbose_name_plural': 'Настройки страницы',
                'ordering': ('modified_at', 'dark'),
            },
        ),
    ]
