# Generated by Django 2.2.17 on 2021-07-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecontent',
            options={'verbose_name': 'контент на страницу главная', 'verbose_name_plural': 'Главная - контент'},
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='content',
            field=models.TextField(blank=True, verbose_name='контент страницы'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='image',
            field=models.ImageField(blank=True, upload_to='mainPhoto', verbose_name='фото/картинка'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='title',
            field=models.CharField(default='Default Title', max_length=120, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата обновления'),
        ),
    ]
