# Generated by Django 2.2.17 on 2021-08-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20210801_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='show_about',
            field=models.BooleanField(default=True),
        ),
    ]
