# Generated by Django 2.2.17 on 2021-08-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_pagecontent_show_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.CharField(blank=True, max_length=256, unique=True, verbose_name='Сылка на Гитхаб')),
                ('vk', models.CharField(blank=True, max_length=256, unique=True, verbose_name='Сылка на vk')),
                ('facebook', models.CharField(blank=True, max_length=256, unique=True, verbose_name='Сылка на facebook')),
                ('instagram', models.CharField(blank=True, max_length=256, unique=True, verbose_name='Сылка на instagram')),
                ('telegram', models.CharField(blank=True, max_length=256, unique=True, verbose_name='телефон')),
                ('WhatsApp', models.CharField(blank=True, max_length=256, unique=True, verbose_name='Телефон для whatsapp')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.RemoveField(
            model_name='pagecontent',
            name='show_about',
        ),
    ]
