# Generated by Django 2.2.17 on 2021-08-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20210801_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='home',
            field=models.TextField(blank=True, verbose_name='Home'),
        ),
    ]
