# Generated by Django 2.2.17 on 2021-08-03 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainpage', '0006_pagecontent_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark', models.BooleanField(default=False, verbose_name='Ночной режим')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата Обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки страницы',
                'verbose_name_plural': 'Настройки страницы',
                'ordering': ('modified_at', 'dark'),
            },
        ),
    ]
