# Generated by Django 2.2.17 on 2021-08-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_auto_20210803_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesettings',
            name='addition_code',
            field=models.TextField(blank=True),
        ),
    ]
