# Generated by Django 2.2.17 on 2021-08-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_pagesettings_insert_addition_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesettings',
            name='addition_code',
            field=models.TextField(blank=True, verbose_name='Доп. код'),
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='insert_addition_code',
            field=models.BooleanField(default=False, verbose_name='добавить код'),
        ),
    ]
