# Generated by Django 2.2.17 on 2021-08-04 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_auto_20210803_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
