# Generated by Django 2.2.17 on 2021-08-04 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0014_auto_20210804_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagesettings',
            name='id',
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_settings', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
