# Generated by Django 2.2.17 on 2021-08-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0015_auto_20210804_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesettings',
            name='tagline',
            field=models.CharField(blank=True, max_length=128, verbose_name='Теги'),
        ),
    ]
