# Generated by Django 2.2.17 on 2021-08-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0020_auto_20210806_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ('-created_at',), 'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='pagecontent',
            options={'ordering': ('-created_at',), 'verbose_name': 'контент на страницу главная', 'verbose_name_plural': 'Главная (контент страницы)'},
        ),
    ]
