# Generated by Django 2.2.17 on 2021-08-12 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0023_auto_20210812_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='telegram',
            new_name='telegram_username',
        ),
    ]
