# Generated by Django 2.2.17 on 2021-09-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0025_auto_20210812_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagesettings',
            name='tagline',
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='background',
            field=models.CharField(blank=True, max_length=128, verbose_name='Background'),
        ),
    ]
