# Generated by Django 2.2.17 on 2021-08-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'M'), ('MALE', 'Ж')], max_length=1, verbose_name='пол'),
        ),
    ]
