# Generated by Django 2.2.17 on 2021-08-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'M'), ('FEMALE', 'Ж')], max_length=1, verbose_name='пол'),
        ),
    ]
