# Generated by Django 2.2.17 on 2021-08-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210804_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('Ж', 'W'), ('O', 'O'), ('T', 'T')], max_length=1, verbose_name='пол'),
        ),
    ]
