# Generated by Django 2.2.17 on 2021-08-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210804_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('W', 'Female'), ('T', 'Transgender'), ('O', 'Other')], max_length=1, verbose_name='пол'),
        ),
    ]
